#define MK_3_SPEED
#define MK_MOMENTARY_ACCEL

#define MK_C_OFFSET_0 4
#define MK_C_INTERVAL_0 16
#define MK_C_OFFSET_UNMOD 10
#define MK_C_INTERVAL_UNMOD 16
#define MK_C_OFFSET_1 20
#define MK_C_INTERVAL_1 16
#define MK_C_OFFSET_2 50
#define MK_C_INTERVAL_2 16

#define MK_W_INTERVAL_0 120
#define MK_W_INTERVAL_UNMOD 30
#define MK_W_INTERVAL_1 10
#define MK_W_INTERVAL_2 2
